### ISSUE TITLE
请求响应拦截不起作用是怎么回事呢？

### ISSUE THREAD

**Issue by andotorg** [ponjs/uni-ajax#10]
// 添加请求拦截器
request.interceptors.request.use(config => {
      try {
        uni.showNavigationBarLoading()
        const token = uni.getStorageSync('token');
        if (token) {
          // 判断是否存在token，如果存在的话，则每个http header都加上token
          config.headers.Authorization = token;
        }
        config.headers.type = "user"; // type:user   是固定的
		console.log(config.headers)
        return config;
      } catch (e) {
		  uni.hideNavigationBarLoading()
		  uni.showToast({
			  title: '发生错误，请稍后重试',
			  position: 'center',
			  icon: 'none',
			  duration: 2000
		  })
      }
  },
  err => {
    uni.hideNavigationBarLoading()
    return Promise.reject(err);
  }
);

**Comment by ponjs** [comment]
首先看你发起请求的方法是否为创建的请求实例，即下面的 `request`。

```diff
// 添加请求拦截器
request.interceptors.request.use(
  config => {
    try {
      /***/
      return config;
    } catch (e) {
      /***/
+     // 这里建议返回 Promise.reject (https://uniajax.ponjs.com/guide/interceptor#拒绝发送请求)
+     return Promise.reject({
+       config,
+       errMsg: 'request:fail intercepted'
+     })
    }
  },
  err => {
    uni.hideNavigationBarLoading();
    return Promise.reject(err);
  }
);
```

**Comment by andotorg** [comment]
找到问题了，还是因为用的headers 改为 header就好了

**Comment by ponjs** [comment]
> 找到问题了，还是因为用的headers 改为 header就好了

那这个 `issues` 描述就有点误导了，我以为是整个拦截器没有执行，原来只是请求头赋值失败
