### ISSUE TITLE
uni-ajax是否可以在原生小程序项目中使用？

### ISSUE THREAD

**Issue by highmind** [ponjs/uni-ajax#15]
目前有一些各个平台的原生小程序，是否可以使用uni-ajax，方便统一网络请求代码

**Comment by ponjs** [comment]
例如在微信原生小程序上可以这样，即修改 [adapter](https://github.com/ponjs/uni-ajax/blob/dev/lib/adapters/http.js)，把 `uni` 换成 `wx`。

```js
import ajax from 'uni-ajax'

const instance = ajax.create({
  adapter(config) {
    return new Promise((resolve, reject) => {
      const requestTask = wx.request({
        ...config,
        complete: result => {
          // 根据状态码判断要执行的触发的状态
          const response = { config, ...result }
          !config.validateStatus || config.validateStatus(result.statusCode)
            ? resolve(response)
            : reject(response)
        },
      })

      config.fetcher?.resolve(requestTask)
    })
  },
})
```

除了上面方法外可以试试在 `app.js` 文件中添加 `uni` 全局常量，不过这个方法我还没试过，可以尝试以下。

```js
globalThis.uni = {
  request: wx.request,
}
```

**Comment by highmind** [comment]
感谢

**Comment by highmind** [comment]
> 例如在微信原生小程序上可以这样，即修改 [adapter](https://github.com/ponjs/uni-ajax/blob/dev/lib/adapters/http.js)，把 `uni` 换成 `wx`。
> 
> ```js
> import ajax from 'uni-ajax'
> 
> const instance = ajax.create({
>   adapter(config) {
>     return new Promise((resolve, reject) => {
>       const requestTask = wx.request({
>         ...config,
>         complete: result => {
>           // 根据状态码判断要执行的触发的状态
>           const response = { config, ...result }
>           !config.validateStatus || config.validateStatus(result.statusCode)
>             ? resolve(response)
>             : reject(response)
>         },
>       })
> 
>       config.fetcher?.resolve(requestTask)
>     })
>   },
> })
> ```
> 
> 除了上面方法外可以试试在 `app.js` 文件中添加 `uni` 全局常量，不过这个方法我还没试过，可以尝试以下。
> 
> ```js
> globalThis.uni = {
>   request: wx.request,
> }
> ```

建议完善一下相关demo，这样 各种原生的 支付宝小程序、抖音小程序、百度小程序、微信小程序 都可以直接使用 uni-ajax替代原生的request等方法，uni-ajax的使用范围会更广
