### ISSUE TITLE
异步拦截器相关错误捕获

### ISSUE THREAD

**Issue by tt-sevth** [ponjs/uni-ajax#4]
- 在异步拦截器`fulfilled`里面抛出错误或者普通拦截器返回 `Promise.reject()`，相关错误会被移交到后一步的拦截器的`rejected`里面处理。目前仅发现问题所在，暂时没想到解决办法。

**Comment by ponjs** [comment]
设计如此，拦截器是链形的，当前面的拦截器返回错误时会进到下一个拦截器的rejected里。注意的是，请求拦截器和响应拦截器是分开的，也就是说请求拦截器发生错误不会进到响应拦截器，而是直接返回到请求方法的错误事件。
