### ISSUE TITLE
怎么发起文件上传请求啊

### ISSUE THREAD

**Issue by luoxiaofeng1029** [ponjs/uni-ajax#7]
怎么发起文件上传请求啊,有demo示例吗

**Comment by ponjs** [comment]
> 怎么发起文件上传请求啊,有demo示例吗

[文档](https://uniajax.ponjs.com/guide/question#%E4%B8%8A%E4%BC%A0%E5%92%8C%E4%B8%8B%E8%BD%BD)里有说明

**Comment by luoxiaofeng1029** [comment]
[https://uniajax.ponjs.com/guide/question#%E4%B8%8A%E4%BC%A0%E5%92%8C%E4%B8%8B%E8%BD%BD](url)
感谢作者..我自己眼瞎没看到,在FAQ里有
