### ISSUE TITLE
文档页面出bug了

### ISSUE THREAD

**Issue by mkdirnow** [ponjs/uni-ajax#9]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17448472/204693677-70b1a08e-873a-453b-81e1-a23a401815ff.png">

**Comment by ponjs** [comment]
页面缓存问题，强刷即可

**Comment by mkdirnow** [comment]
换了个没有访问过该网站的云桌面，一样的问题
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17448472/204705590-a2e20b39-3e86-4e8b-9122-4e2f7c31b1bb.png">

**Comment by ponjs** [comment]
已初步修复，这是 nginx 伪静态规则错误问题
